const sidebars = {
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  startSidebar: [{ type: 'autogenerated', dirName: 'getting_started' }],
  introSidebar: [{ type: 'autogenerated', dirName: 'introduction' }],
  developSidebar: [{ type: 'autogenerated', dirName: 'develop_guide' }],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
};

module.exports = sidebars;

